name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        run: |
          rsync -e "ssh -i ~/.ssh/id_rsa" -r --delete-after --quiet $GITHUB_WORKSPACE/ ${{ secrets.USERNAME }}@${{ secrets.HOST_DNS }}:/var/www/html/
